config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'

  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
      @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render :new
    end
  end

  def edit
    @todo = Todo.find(params[:id])

  end

  def update

  end

  def delete

  end


  private

  def todo_params
    params.require(:todo).permit(:title, :body, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>To Do List</h1>
  <% @todos.each do |todo| %>
<h2><%= todo.title %></h2>
<h3><%= todo.completed %></h3>
<p><%= todo.body %></p>
  <% link_to 'Show todo', todo_path(todo) %>
<% end %>

<%= link_to 'New To do', new_todo_path %>

app/views/todos/new.html.erb
<h1>Form for To Do List</h1>
<%= form_for @todo do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :completed %>
<%= f.text_field :completed %>

<%= f.label :body%>
<%= f.text_field :body %>

<%= f.submit %>
<% end %>

app/views/todos/show.html.erb
<h1>Show</h1>
<h2><%= @todo.title %></h2>
<h3><%= @todo.completed%></h3>
<p><%= @todo.body %></p>
<%= link_to 'Back', todos_path %>